[package]
name = "realtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
supabase-js-rs = { version = "0.1.2" }
wasm-bindgen = "0.2.83"