name: Run Supabase Migration Test

on:
  push:
    branches:
      - main
    paths:
      - postgres/migrations/**
      - postgres/benches/**

  pull_request:
    branches:
      - main
    paths:
      - postgres/migrations/**
      - postgres/benches/**

jobs:
  migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create .env file
        run: |
          touch .env.ci
          echo SUPABASE_DB=${{ secrets.SUPABASE_DB }} >> .env.ci
          echo SUPABASE_DB_USER=${{ secrets.SUPABASE_DB_USER }} >> .env.ci
          echo SUPABASE_DB_PORT=${{ secrets.SUPABASE_DB_PORT }} >> .env.ci
          echo SUPABASE_DB_PASSWORD=${{ secrets.SUPABASE_DB_PASSWORD }} >> .env.ci

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            AppFlowy-Supabase/postgres
          cache-all-crates: true

      - name: Run all up migrations
        run: |
          cargo run database reset .env.ci no-verify

      - name: Run migration tests
        working-directory: ./postgres/migrations_tests
        env:
          PGHOST: ${{ secrets.SUPABASE_DB }}
          PGPORT: ${{ secrets.SUPABASE_DB_PORT }}
          PGUSER: ${{ secrets.SUPABASE_DB_USER }}
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          PGDB: postgres
        run: |
          ./check
          ./af_user
          ./af_collab_update

      - name: Run benchmark (insert into af_collab_update)
        working-directory: ./postgres
        env:
          PGHOST: ${{ secrets.SUPABASE_DB }}
          PGPORT: ${{ secrets.SUPABASE_DB_PORT }}
          PGUSER: ${{ secrets.SUPABASE_DB_USER }}
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: cargo bench
